### ISSUE TITLE
usage doc feedback

### ISSUE THREAD

**Issue by karelv** [igor-raits/sphinxcontrib-issuetracker#6]
https://github.com/lunaryorn/sphinxcontrib-issuetracker/blob/0.11/doc/usage.rst
Probably red and green are swapped in your css example?

**Comment by karelv** [comment]
Exactly the text is update, but not the style sheet

> .xref.issue {
>     color: green;
> }
> 
> .xref.issue.closed {
>     color: red;
> }

**Comment by swsnr** [comment]
Does the color matter?  I mean it's an example after all…

**Comment by swsnr** [comment]
I mean, the colors don't really matter, as long as the text and the code match… which they do now.

**Comment by karelv** [comment]
ok fine to me.
