### ISSUE TITLE
Need help with offline usage

### ISSUE THREAD

**Issue by opoplawski** [igor-raits/sphinxcontrib-issuetracker#9]
I'm packaging StarCluster for Fedora, which has just started using the issuetracker extension.  For security and reproducibility reasons, the Fedora builders do no have network access, so my build is failing with:

```
Exception occurred:
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/jtriley/StarCluster/issues/392 (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
```

Do you have any ideas as to how we could support builds in this situation?

**Comment by swsnr** [comment]
@opoplawski Patch this extension.  Really, its whole point and purpose is to retrieve issue information from foreign host, so “offline” usage doesn't make much sense.  

If you'd just like to have links to your issues, use the built-in extlinks extension of Sphinx, or write your own transformer in your `conf.py`.  Feel free to copy code from this extension if you want.
